### ISSUE TITLE
Make Docker image names configurable

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#71] opened 2015-06-05 10:16 UTC
The scheduler should use mesos/elasticsearch-cloud-mesos by default but you should be able to override this via a command line option.

**Comment by frankscholten** [comment] 2015-06-20 01:30
Both scheduler and executor images should be configurable and use defaults.

**Comment by philwinder** [comment] 2015-08-20 13:43
Duplicate of #111.

**Comment by philwinder** [comment] 2015-08-24 14:44
Fixed in #235

**Closed by philwinder** 2015-08-24 14:44 UTC
Labels: configuration, enhancement, improvement
