### ISSUE TITLE
Tasks getting stuck at TASK_STAGING

### ISSUE THREAD

**Issue by Aerlinger** [mesos/elasticsearch#249] opened 2015-08-26 04:19 UTC
I've deployed elasticsearch several times on DCOS via the marathon configuration. Each time I've noticed that tasks don't seem to get past the "TASK_STAGING" stage. I've also noticed that not all of my ES nodes show up in the node dropdown field within the Query manager on the main page.

Here's what I see on the main page:

![image](https://cloud.githubusercontent.com/assets/604138/9485481/b27d1ac4-4b87-11e5-8ac8-c2136926789c.png)

Also, I only see one of the 5 nodes under the tasks section:

![image](https://cloud.githubusercontent.com/assets/604138/9485431/e92eb7d6-4b86-11e5-8866-7222fef35c72.png)

I also tried deploying with the same configuration but only with 3 ES nodes all three showed up as "TASK_STAGING"

**Comment by frankscholten** [comment] 2015-08-26 09:31
Thanks for reporting this @Aerlinger!

On our cluster the tasks are also all in TASK_STAGING so this is a bug. However on our side the Elasticsearch and Mesos GUIs show the same number of tasks. Perhaps you can debug the UI in the browser with dev tools / Firebug or check the API calls at the scheduler? See the APIary docs http://docs.elasticsearchmesosui.apiary.io/

**Comment by philwinder** [comment] 2015-08-26 09:33
Duplicate of #206
Will be fixed soon. Thanks @Aerlinger.

**Closed by philwinder** 2015-08-26 09:33 UTC
Labels: bug
