### ISSUE TITLE
Support new mesos persistent volumes

### ISSUE THREAD

**Issue by SEJeff** [mesos/elasticsearch#548] opened 2016-04-01 18:35 UTC
This would allow the framework to request a persistent volume. If the slave dies or app is killed, the scheduler can restart the app on the same physical node. This prevents having to re-copy the data everywhere and allows using the old app instance sandbox instead.

Here are the [Mesos docs](http://mesos.apache.org/documentation/latest/persistent-volume/) and [Marathon docs](https://mesosphere.github.io/marathon/docs/persistent-volumes.html) on this feature.

**Comment by siddharthist** [comment] 2016-04-08 18:40
Duplicate of #306

**Comment by SEJeff** [comment] 2016-04-08 22:48
Thanks @siddharthist

**Closed** 2016-04-08 22:48 UTC
Labels: enhancement
