### ISSUE TITLE
ES_HEAP_SIZE no longer supported in 5.0 GA

### ISSUE THREAD

**Issue by andreimc** [mesos/elasticsearch#590] opened 2016-11-07 21:03 UTC
https://github.com/mantl/mantl/issues/1852

tarting task elasticsearch_worker-002.node.consul_20161107T203308.556Z
Error: encountered environment variables that are no longer supported
Use jvm.options or ES_JAVA_OPTS to configure the JVM
ES_HEAP_SIZE=1792m: set -Xms1792m and -Xmx1792m in jvm.options or add "-Xms1792m -Xmx1792m" to ES_JAVA_OPTS

**Comment by maria** [comment] 2016-11-08 14:01
I get the same error with the latest version of Elasticsearch 5.0, the reference is https://www.elastic.co/guide/en/elasticsearch/reference/master/heap-size.html.

**Comment by dinoba** [comment] 2016-11-10 15:35
I have tried (over marathon) like this


{
  "id": "elasticsearch",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler",
      "network": "HOST"
    }
  },
  "args":
  [
	"--zookeeperMesosUrl", "zk://192.168.1.31:2181,192.168.1.32:2181,192.168.1.33:2181/mesos"
  ],
  "cpus": 0.5,
  "mem": 1024,
  "env": {
    "JAVA_OPTS": "-Xms2g -Xmx2g",
	**"ES_JAVA_OPTS": "-Xms2g -Xmx2g"**
  },
  "instances": 1,
  "ports": [
        31100, 31101, 31102
    ]    
}

but it doesn't work. I get some really strange errors

**Comment by emanuelemaffeo** [comment] 2016-11-23 09:44
I've got the same problem, any suggestion? Maybe elasticsearch 5 has some sort of incompatibility with the framework?

**Comment by gbjk** [comment] 2016-11-25 16:22
I just wanted to quickly chime in.

We encountered the same thing.

The issue is in the scheduler itself, when it dispatches to create the executors, it's hard coded to send ES_HEAP_SIZE.

Changing the marathon options for JAVA_OPTS/ES_JAVA_OPTS won't help, they only effect the scheduler's container.

We're looking at fixing this in the scheduler and we'll submit a PR if we're successful.
It's just a case of changing it so that it uses ES_JAVA_OPTS instead in the environmentVariables

**Comment by dinoba** [comment] 2016-11-28 06:24
add this to args array, to use older version

    "--elasticsearchDockerImage", "elasticsearch:2.4.1"

**Comment by nubunto** [comment] 2016-11-28 11:24
Started a pull request for this at mesos/elasticsearch#592

**Comment by frankscholten** [comment] 2016-12-01 21:50
https://github.com/mesos/elasticsearch/pull/592 has been merged. Thanks all for the discussion and @nubunto for the PR!

**Closed by frankscholten** 2016-12-01 21:50 UTC

**Comment by SriganeshNk** [comment] 2017-09-19 04:55
Is there any solution to this? I'm facing the same issue when trying to deploy ES on mesos.

**Comment by minafarid** [comment] 2017-11-11 05:20
ditto, same problem
