### ISSUE TITLE
Scale cluster horizontally

### ISSUE THREAD

**Issue by keithchambers** [mesos/elasticsearch#93] opened 2015-06-19 22:27 UTC

**Comment by jhftrifork** [comment] 2015-09-08 15:05
Currently the scale of the Elasticsearch cluster is configured with the `--elasticsearchNodes` command-line argument to the scheduler. This number determines whether the scheduler will accept a resource offer: it will attempt to launch ES nodes until it reaches that number of them.

Scaling an ES cluster requires changing this value dynamically. After launching the scheduler, there is no way to change this value except to launch a new scheduler for the same framework, configured with a different `--elasticsearchNodes` parameter. This is ugly.

We want a way to make a request to the scheduler to update the value. Presumably this would be an HTTP API. We currently expose our configuration via `/v1/cluster`, which accepts `GET` requests, like this:

```
> curl http://172.17.0.107:31100/v1/cluster | jq .
{
  "name": "esdemo",
  "configuration": {
    "EexecutorImage": "mesos/elasticsearch-executor",
    "FrameworkName": "elasticsearch",
    "FailoverTimeout": 2592000,
    "MesosStateZKURL": "172.17.0.106:2181",
    "ExecutorTimeout": 60000,
    "ExecutorHealthDelay": 30000,
    "ElasticsearchSettingsLocation": "",
    "Cpus": 1,
    "FrameworkState": "org.apache.mesos.elasticsearch.scheduler.state.FrameworkState@2265c7ac",
    "FrameworkZKURL": "172.17.0.106:2181/mesos",
    "FrameworkZKTimeout": 30000,
    "Mem": 256,
    "TaskName": "esdemo",
    "Version": "0.4.0",
    "State": "org.apache.mesos.elasticsearch.scheduler.state.SerializableZookeeperState@2d82dc93",
    "ElasticsearchClusterName": "mesos-ha",
    "MesosZKURL": "zk://172.17.0.106:2181/mesos",
    "FrameworkId": "20150908-144309-1778389420-5050-25-0000",
    "FrameworkRole": "*",
    "Disk": 1024,
    "WebUiPort": 31100,
    "ExecutorForcePullImage": false,
    "DataDir": "/var/lib/mesos/slave/elasticsearch",
    "ElasticsearchNodes": 3
  }
}
```

The key `configuration.ElasticsearchNodes` tells us the current scale.

It would make sense for our API to accept `PUT` requests to change configuration values like this one. It probably doesn't make sense to accept monolithic updates to `/v1/cluster`, though; especially since some values are not obviously updateable (e.g. `WebUiPort`).

I suggest that instead we extend the API with resources like:

```
/v1/cluster/elasticsearchNodes
/v1/cluster/executorTimeout
...
```

where the resource names are the same as the command-line parameter names, and which will accept `PUT` requests if they are updateable.

So the work for this issue would just be to add a resource `/v1/cluster/elasticsearchNodes`, which accepts `PUT` requests with a new number.

If the number is increased, the scheduler will try to create more ES nodes, but if the number is decreased, it will not currently try to kill off any nodes. Killing off ES nodes to downscale is more work and requires some thought. So to begin with, we will just up-scale, and accept that more ES nodes may be running than desired (I suppose they can be manually killed if necessary).

@tymofii-polekhin Does this sound reasonable?

**Comment by philwinder** [comment] 2015-12-10 10:23
Duplicate of #322

**Closed by philwinder** 2015-12-10 10:23 UTC
Labels: scalability

**Comment by rsingh2411** [comment] 2016-01-13 09:24
I have a query with this change can we horizontally scale using gui or is it being provisioned through rest api. Please let me know the parameters and api which can be used , if GUI option is still WIP

**Comment by philwinder** [comment] 2016-01-13 12:45
@rsingh2411 You can scale through the gui or REST. The endpoint will be /v1/cluster/elasticsearchNodes
PUT with and int to change the number of nodes. GET to get the current number of nodes.

**Comment by rsingh2411** [comment] 2016-01-13 12:57
Hey Phil,

I tried the following URL
http://<ip>:31100/v1/cluster/elasticsearchNodes?to=2

I recieved following error
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Request method &#39;PUT&#39; not supported

**Comment by philwinder** [comment] 2016-01-13 13:01
Note that feature isn't available until the 0.7.0 release. I assume you have installed a custom version based upon a master commit?

But the scale number isn't a parameter, it's the data:
curl X.X.X:31000/v1/cluster/elasticsearchNodes -d '2'
I believe. Although my memory might be wrong. :-)

**Comment by philwinder** [comment] 2016-01-13 13:05
This is how our tests do it:
```
HttpResponse<JsonNode> response = Unirest.put("http://" + ipAddress + ":" + WEBUI_PORT + "/v1/cluster/elasticsearchNodes").header("Content-Type", "application/json").body(newNumNodes.toString()).asJson();
```
So yes, you need to send the number of nodes as the body data.

**Comment by rsingh2411** [comment] 2016-01-13 13:08
I think you are right... I might be using an old version... .Please let me know the release date of 0.7.0 if possible

**Comment by philwinder** [comment] 2016-01-13 13:09
Very, very soon. Maybe today, probably tomorrow. :-)

**Comment by rsingh2411** [comment] 2016-01-13 13:12
Cool!!!!!! thats great news..
