### ISSUE TITLE
Upgrade to Mesos 0.23 to support persistent volumes

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#228] opened 2015-08-21 10:15 UTC

**Comment by frankscholten** [comment] 2015-08-25 07:42
Persistent volumes depends on reservation and authorization but authorization support in Elasticsearch is blocked #218

**Comment by a-nldisr** [comment] 2015-09-21 08:44
Hi, 

Version 0.24.0 is released, are there plans to skip 0.23.0 and go for 0.24.0 instead?

**Comment by philwinder** [comment] 2015-10-27 10:58
Duplicate of #338

**Closed by philwinder** 2015-10-27 10:58 UTC
Labels: blocked, enhancement

**Comment by sarwarbhuiyan** [comment] 2016-09-19 17:15
Did you mean #306
