### ISSUE TITLE
Allow to configure docker image name

### ISSUE THREAD

**Issue by kamaradclimber** [mesos/elasticsearch#232] opened 2015-08-21 16:11 UTC
In our organization, we'd like to provide our own docker image (to use our distribution for instance).

It would be interesting to have an option to configure the image name.

**Comment by frankscholten** [comment] 2015-08-24 06:06
Duplicate of https://github.com/mesos/elasticsearch/issues/71

**Closed by frankscholten** 2015-08-24 06:06 UTC
