### ISSUE TITLE
Configure overall cluster disk size

### ISSUE THREAD

**Issue by frankscholten** [mesos/elasticsearch#155] opened 2015-07-16 11:15 UTC
As a user I want to configure the overal disk size of the cluster.

Internally the framework will compute the minimum disk size per offer by taking the overal disk size and divide it by the number of nodes (-n)

```
dcos install  elasticsearch  —size=2TB 
```

**Comment by philwinder** [comment] 2015-08-20 13:43
Duplicate of #111

**Comment by philwinder** [comment] 2015-08-24 14:43
Fixed in pull/235

**Comment by philwinder** [comment] 2015-08-24 14:43
#235

**Closed by philwinder** 2015-08-24 14:43 UTC
Labels: configuration, enhancement
