### ISSUE TITLE
Support deploying multiple Elasticsearch clusters to single Mesos cluster

### ISSUE THREAD

**Issue by keithchambers** [mesos/elasticsearch#91] opened 2015-06-19 22:26 UTC

**Comment by mwl** [comment] 2015-08-06 08:30
Task is allocated to @jhftrifork

**Comment by jhftrifork** [comment] 2015-08-06 09:10
First thing, I'll test it to find out if/why this doesn't work already. Probably something to do with framework names and/or framework ids.

**Comment by frankscholten** [comment] 2015-08-19 10:04
For this to work the clustername needs to be configurable. Currently the clustername is 'elasticsearch'

**Comment by philwinder** [comment] 2015-08-19 10:08
Depends on configuration epic. See https://github.com/mesos/elasticsearch/labels/configuration

**Comment by philwinder** [comment] 2015-08-20 13:43
Duplicate of #111

**Comment by philwinder** [comment] 2015-08-24 14:44
Fixed in #235

**Closed by philwinder** 2015-08-24 14:44 UTC
Labels: configuration, enhancement, Medium
